name: satorio
description: Sator mobile client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+58

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  get_storage: ^2.0.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.0.3
  sprintf: ^6.0.0
  circular_countdown_timer: ^0.2.1
  timer_count_down: ^2.2.1
  url_launcher: ^6.1.0
  pin_code_fields: ^7.4.0
  qr_code_scanner: ^0.7.0
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  share_plus: ^4.0.3
  firebase_core: ^1.14.0
  firebase_database: ^9.0.10
  firebase_dynamic_links: ^4.1.2
  firebase_messaging: ^11.2.12
  firebase_remote_config: ^2.0.3
  grouped_list: ^4.2.0
  webview_flutter: ^2.0.13
  cached_network_image: ^3.2.0
  lottie: ^1.2.2
  visibility_detector: ^0.2.2
  scroll_to_index: ^2.1.1
  flutter_staggered_grid_view: ^0.4.1
  youtube_player_flutter: ^8.0.0
  better_player: ^0.0.81
  flutter_secure_storage: ^5.0.2
  local_auth: ^1.1.11
  flutter_switch: ^0.3.2
  flutter_idensic_mobile_sdk_plugin: ^1.19.2
  package_info_plus: ^1.4.2
  dart_nats: ^0.3.5
  fast_rsa: ^3.4.6
  cryptography: ^2.0.5
  confetti: ^0.6.0
  image: ^3.1.3
  equatable: ^2.0.3
  flutter_inapp_purchase: ^5.1.2
  connectivity_plus: ^2.3.0
  app_settings: ^4.1.6
  device_info_plus: ^3.2.3
  webfeed: ^0.7.0
  flutter_html: ^3.0.0-alpha.3
  flutter_unity_widget: ^2022.1.0+4
  firebase_analytics: ^9.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lottie-anim/
    - images/
    - images/bg/
    - images/avatar/
    - images/show/
    - images/smile/
    - images/settings/

  fonts:
    - family: SatorIcons
      fonts:
        - asset: fonts/SatorIcons.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/Inter-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/Inter-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          style: normal
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: fonts/Inter-Black.ttf
          style: normal
          weight: 900
